### ISSUE TITLE
GTransCD: Graph Transformer-Guided Multi-temporal Information United Framework for Hyperspectral Image Change Detection

### ISSUE THREAD

**Issue by Mr-zero666** [zxylnnu/GeSANet#1]
前辈可以再次分享您这篇文献的代码吗？不胜感激

**Comment by zxylnnu** [comment]
感谢你的关注，我会加速整理。

**Comment by zxylnnu** [comment]
感谢你的关注，我会加快速度整理。

**Comment by YJYJ7** [comment]
didididi

**Comment by Mr-zero666** [comment]
收到，感谢前辈的代码资源

**Comment by YJYJ7** [comment]
您好，请问GTransCD的代码是否也可以发我呢一份呢？我看不懂文章。昨天我给前辈留言了，还没收到回复，如果能转发给我，不胜感激。
________________________________
发件人: NanYuan-dxy ***@***.***>
发送时间: 2024年3月31日 10:48
收件人: zxylnnu/GeSANet ***@***.***>
抄送: YJYJ7 ***@***.***>; Comment ***@***.***>
主题: Re: [zxylnnu/GeSANet] GTransCD: Graph Transformer-Guided Multi-temporal Information United Framework for Hyperspectral Image Change Detection (Issue #1)


收到，感谢前辈的代码资源

―
